### PR TITLE
Shell autocompletion

### PR DESCRIPTION
**Pull request by eXistenZNL**
## What

Autocompletion for ZSH and Bash

## How to test

Follow the README.md and see if it works.

## Why

Because we can always be a little more lazy!

### CODE REVIEW

**Comment by rtuin** [comment]
This is awesome man!
@renatomefi you made a similar script for Pla, right? Do you have any thoughts on this one?

**Comment by renatomefi** [comment]
Oh that's cool! The difference in here is Stefan is reading directly from the pla file, and only in the current directory which is different from the pla behavior.
I like to make autocompletes by executing the command, because any logic like default options, parent configuration files or anything in the future would still be compatible!
But that's just a matter of taste! hehe

That's the one I've done: https://github.com/renatomefi/pla-zsh-plugin/blob/master/pla.plugin.zsh

**Comment by eXistenZNL** [comment]
@renatomefi has a point, Pla supports sub-directories as well which is not covered by my solution. I will simply steal Renato's solution to getting the commands, mention him as an author, update both the ZSH and Bash scripts, and update the PR. that way it is shipped with Pla itself instead of a separate project =)

**Comment by eXistenZNL** [comment]
Despite my best efforts I never got around to do it, and since then pla has been replaced by make at the company I work for. I do not intend to fix this anymore, so closing this PR.

**Pull request closed without merging**
